export const FETCH_ROUTES_SUCCESS = "FETCH_ROUTES_SUCCESS";
export const FETCH_ROUTE_PENDING = "FETCH_ROUTE_PENDING";
export const DELETE_ROUTE = "DELETE_ROUTE";
export const FETCH_ROUTE_SUCCESS = "FETCH_ROUTE_SUCCESS";
export const UPDATE_ROUTE = "UPDATE_ROUTE";
export const ADD_ROUTE = "ADD_ROUTE";

export const FETCH_CATEGORIES_PENDING = "FETCH_CATEGORIES_PENDING";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";

export const LOAD_LOCATIONS = "LOAD_LOCATIONS";
export const LOAD_LOCATION = "LOAD_LOCATION";
