# Generated by Django 2.2.7 on 2019-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
    ]
